============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/stidsem4/iut/2021/controle/victor.seng/c16_03
collected 7 items

test_16_03.py F......                                                    [100%]

=================================== FAILURES ===================================
_____________________________ Test1603sute.test_10 _____________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_10>

    def test_10(self):
        try:
            from .main  import Note
        except:
           assert False
        try:
            Note.vider()
        except:
            assert False
        note1 = Note('elv1', 'xx', 12)
        note1 = Note('elv1', 'yy', 13)
        note1 = Note('elv1', 'yy', 14)
        note1 = Note('elv2', 'zz', 13)
        try:
>           assert Note.moyenne('elv1') == 13
E           AttributeError: type object 'Note' has no attribute 'moyenne'

test_16_03.py:106: AttributeError
----------------------------- Captured stdout call -----------------------------
[('eleve1', 'math', 13), ('eleve1', 'physique', 15), ('eleve1', 'math', 13), ('eleve1', 'eco', 12), ('eleve1', 'eco', 13), ('eleve1', 'math', 12)]
13.0
[('eleve1', 'math', 13), ('eleve1', 'math', 13), ('eleve1', 'math', 12)]
12.666666666666666
12.666666666666666
eleve1
math
13
eleve eleve1 matiere math note 13
La note est de 13 pour l'eleve1 en math.
eleve eleve1 matiere math note 13
eleve eleve1 matiere physique note 15
eleve eleve1 matiere math note 13
eleve eleve1 matiere eco note 12
eleve eleve1 matiere eco note 13
eleve eleve1 matiere math note 12
eleve eleve2 matiere math note 13
eleve eleve2 matiere math note 14
eleve eleve1 matiere math note 13
eleve eleve1 matiere math note 13
eleve eleve1 matiere physique note 15
eleve eleve1 matiere math note 13
eleve eleve1 matiere eco note 12
eleve eleve1 matiere eco note 13
eleve eleve1 matiere math note 12
eleve eleve2 matiere math note 13
eleve eleve2 matiere math note 14
13.11111111111111
=========================== short test summary info ============================
FAILED test_16_03.py::Test1603sute::test_10 - AttributeError: type object 'No...
========================= 1 failed, 6 passed in 0.07s ==========================
